[package]
name = "rustisbetter"
version = "0.1.1"
authors = ["Ethan McCue <emccue@live.com>"]
edition = "2021"
resolver = "2"

[dependencies]
ggez = "0.7" # ^0.7 broke everything
rand = "0.7.3"

[profile.dev]
opt-level = 1
